# scripts/docker/docker-compose.yml
version: "3.8"

services:
  ovms-vlm:
    image: openvino/model_server:latest
    container_name: ovms_phi3_vision
    ports:
      - "8001:8001"
    volumes:
      - ../../models/OpenVINO:/models
    command: >
      --model_path /models/Phi-3.5-vision-instruct-int4-ov
      --model_name phi3_vision
      --rest_port 8001
    restart: unless-stopped

  ovms-llm:
    image: openvino/model_server:latest
    container_name: ovms_deepseek_llm
    ports:
      - "8002:8002"
    volumes:
      - ../../models/OpenVINO:/models
    command: >
      --model_path /models/DeepSeek-R1-Distill-Qwen-7B-int4-ov
      --model_name deepseek_llm
      --rest_port 8002
    restart: unless-stopped